[STRAWBERRY]
json = true
prompt = """how many “r”s are in the word “strawberry. Give the output as json with key: “count” and a number"""
answer = {count = 3}

[BEOORDELAAR]
json = false
answer_contains = 'boven de zuiger'
system = """Je bent een ervaren leraar autotechniek. Je doel is om mij zo goed en zo efficiënt mogelijk {subject} bij te brengen.
Ik volg een studie autotechniek op MBO of community college niveau.
Je bent vriendelijk, behulpzaam. Je schrijft in het Nederlands."""
prompt = """Ik wil dat je mijn antwoord in een examen beoordeelt.
Beschouw de volgende vraag en het antwoord van een expert, beiden tussen triple quotes:

Vraag: '''Wat laat het indicateurdiagram zien?'''
Expert antwoord: '''Het drukverloop boven de zuiger tijdens één arbeidscyclus.'''

Volg de volgende stappen:

1. Beschouw mijn antwoord: '''De druk in de zuiger.'''
en mijn correctie: '''tijdens een cyclus van de motor'''
Geef hier geen output over.

2. Voeg mijn antwoord en mijn correctie samen tot één antwoord.
Waar correctie en antwoord elkaar tegen spreken, kies je voor de correctie.
Geef hier geen output over.

3. Beoordeel dit samengevoegde antwoord door het te vergelijken met het antwoord van de expert.
Geef in je beoordeling aan waar ik kennis mis en leg uit hoe ik deze hiaten kan minimaliseren met behulp van voorbeelden uit de echte wereld.
Geef deze beoordeling als output.
Maak je tekst leerzaam, motiverend en inspirerend maar gebruik eenvoudige taal.
Gebruik maximaal 80 woorden.
Antwoord in het Nederlands."""


[VERTALER]
json = false
answer_contains = '%naam%'
system = """Je bent een vertaler. Je vertaalt software die bedoeld is voor de training van automonteurs.
De vertalingen bestaan soms uit hele zinnen maar soms ook uit losse woorden."""
prompt = """Vertaal de volgende 3 teksten naar Engels.

1 [[De eerste zin bestaat@@uit twee regels en nog een lege regel aan het eind@@]]
2 [[We luisterden naar de band maar hoorden er geen lucht uit lopen.]]
3 [[@@Hallo %naam%. Je hebt %aantal% nieuwe berichten.]]

**Belangrijke instructies voor de vertaling:**

- **Alleen tekst vertalen:** Vertaal enkel de tekst die zich bevindt tussen de dubbele vierkante haakjes `[[` en `]]`.
- **Behoud van speciale tekens:** Alle spaties, tabs, leestekens, `@@`, `###`, symbolen, en andere speciale tekens moeten exact behouden blijven zoals ze in de oorspronkelijke tekst staan.
- **Formatteerkenmerken behouden:** Als een tekst eindigt op `@@`, de vertaalde tekst moet ook eindigen op `@@`.

**Vertaalverzoek:**

Geef de vertalingen terug met behoud van de originele structuur, nummering, en formatteerkenmerken."""

[MULTI_VERTALER]
json = true
system = """You are a professional translator specialized in translating technical training PowerPointdocuments.

## Target audience
The texts requiring translation are technical training materials specifically designed for sweepers.

These training documents delve into a variety of intricate topics, including hydraulic systems and
electrical systems, which are essential for the operation and control of the sweepers.

The training is meticulously structured to cater to mechanics at different levels of expertise,
from beginners who are just starting their careers to seasoned professionals who have extensive experience in the field.

Each section of the training is tailored to enhance the understanding and skills of the mechanics,
providing them with the necessary knowledge to perform maintenance, troubleshoot issues,
and optimize the performance of the sweepers.

The goal of these trainings is to equip the mechanics with a thorough understanding of the technical aspects of sweepers,
enabling them to handle various challenges and improve the overall efficiency and reliability of the machines."""
prompt = """Translate this JSON list with 70 texts into Dutch.

[[0, "How to make the RAVO R5e safe to work on."], [1, "How to apply the Factory Standard guidelines."], [2, "When you should use personal protection equipment."], [3, "How to disable the high voltage system safely in accordance "], [4, "     with the "], [5, "13-step"], [6, " procedure."], [7, "Goals for this training"], [8, "Autosized"], [9, "The most important is "], [10, "that"], [11, "participants"], [12, " feel "], [13, "confident"], [14, "that"], [15, "they"], [16, "can"], [17, "safely"], [18, " handel "], [19, "the"], [20, "electric"], [21, " machine "], [22, "and"], [23, "the"], [24, "safety"], [25, " procedure. "], [26, "Goals for this training"], [27, "According to the Factory Standard there are 3 kinds of technical levels:"], [28, "Level 1    Non-EV trained technician (Layman)"], [29, "Level 3   EV-Workshop Supervisor (main responsible person) ("], [30, "ev"], [31, "-WS) "], [32, "  At least EV-PP skilled"], [33, "Level 2   EV-Professional Person ("], [34, "ev"], [35, "-PP)"], [36, "The designation documents:"], [37, "There must be a "], [38, "written agreement "], [39, "between employer and employee."], [40, "The person designating must be satisfied that:"], [41, "The person being designated "], [42, "meets the conditions"], [43, "The person designated must be satisfied that:"], [44, "He/she "], [45, "meets the conditions"], [46, " and that he/she has the "], [47, "necessary powers and resources"], [48, "."], [49, "The document must at least contain:"], [50, "The person\u2019s name, effective and expiring date, qualification and vehicle type."], [51, "Factory standard"], [52, "You must be authorized to work on electric vehicles in accordance with the local standards."], [53, "The definition of the levels may differ depending on the standard of each country."], [54, "There"], [55, " is no "], [56, "diffrence"], [57, "between"], [58, "Lvel"], [59, " 2 "], [60, "and"], [61, " 3 "], [62, "only"], [63, "that"], [64, " level 3 has "], [65, "the"], [66, "responsibilities"], [67, ". "], [68, "Factory standard"], [69, "HV-system "]]

If there are spaces or punctuation marks in the text, keep them intact in the translated text.
Translate all 70 texts.

If possible, try not to make the translations longer than the original texts.
Your output should be JSON again, with the key 'translations' and the value being the list in the same structure as the input.
Note! The output JSON must also contain exactly 70 elements."""
answer_contains = "verantwoordelijkheden"

[BIRMEES]
json = false
answer_contains = "မီး"
prompt = """Vertaal de volgende tekst naar het Birmees: Een zuigmotor vereist regelmatig onderhoud om optimale prestaties en een lange levensduur te garanderen. Het begint met het controleren en vervangen van smeerolie, omdat olie niet alleen wrijving vermindert maar ook vuildeeltjes afvoert en de interne componenten koelt. Het olie- en oliefilter dienen doorgaans om de 10.000 tot 15.000 kilometer vervangen te worden, afhankelijk van gebruiksomstandigheden en fabrikantenspecificaties. Daarnaast is het controleren en reinigen of vervangen van het luchtfilter belangrijk; een verstopt filter vermindert de luchttoevoer, wat leidt tot onvolledige verbranding en vermogensverlies. Ook de bougies moeten op tijd worden nagezien, omdat versleten bougies een onregelmatige ontsteking en verhoogd brandstofverbruik veroorzaken.
Verder is het van belang de koelvloeistof op peil te houden en periodiek te verversen, aangezien oververhitting ernstige motorschade kan veroorzaken. De aandrijfriemen en kettingen moeten regelmatig op slijtage of spanning worden gecontroleerd, omdat deze een cruciale rol spelen in de timing en aandrijving van hulpaggregaten. Brandstoffilters dienen schoon te zijn om verstoppingen en schade aan de injectoren te voorkomen. Tot slot kan preventief onderhoud, zoals het meten van de compressiedruk en het inspecteren van de cilinderwanden op slijtage, helpen om beginnende problemen vroegtijdig te signaleren. Zo blijft een zuigmotor betrouwbaar, efficiënt en veilig in gebruik."""

[APPLES]
json = true
answer = {oplossing = 11}
prompt = """Ik had een aantal appels. Ik verloor er één. Daarna gaf ik de helft van wat ik over had weg.
Daarna at ik er drie op. Toen had ik er nog twee over. Hoeveel appels had ik aan het begin?

Werk stap voor stap aan dit probleem.
Geef me de output als json met als key: "oplossing" en als waarde het aantal appels.
Maar geef alleen json als output terug. Geen andere tekst ervoor of erna."""


[BALKON1]
prompt = """Geef me de oppervlakte van het balkon in vierkante meter. Geef je antwoord in json met als
key: 'oppervlakte' en als waarde de oppervlakte in vierkante meter afgerond op 2 cijfers achter de komma."""
image = 'input/balkon1.png'
json = true
answer = {oppervlakte = 6.84}

[TERRAS2]
prompt = """Geef me de oppervlakte van het dakterras in vierkante meter. Geef je antwoord in json met als
key: 'oppervlakte' en als waarde de oppervlakte in vierkante meter afgerond op 4 cijfers achter de komma."""
image = 'input/terras2.png'
json = true
answer = {oppervlakte = 3.7275}

[TERRAS3]
prompt = """Geef me de oppervlakte van het dakterras in vierkante meter. Geef je antwoord in json met als
key: 'oppervlakte' en als waarde de oppervlakte in vierkante meter afgerond op 4 cijfers achter de komma."""
image = 'input/terras3.png'
json = true
answer = {oppervlakte = 3.7275}

[HAZES]
prompt = """Geef me de naam van de Amsterdamse volkszanger uit de Pijp wiens kinderen ook zangers zijn."""
answer_contains = 'André Hazes'
json = false

[VERSCHILLEN1]
prompt = """Kijk goed naar deze twee afbeeldingen en geef me de 12 verschillen.
Geef niet meteen antwoord maar bekijk elke regio van de afbeelding zorgvuldig. Bekijk per regio welke verschillen je ziet.
Als je de verschillen hebt gevonden, check ze dan. Zijn de afbeeldingen op dat punt echt verschillend?
Check tenslotte of je nog verschillen hebt gemist. Ik wil ze alle 12 hebben! Dat is heel belangrijk.
Stel geen vragen.
"""
image = ['input/verschillen1a.png', 'input/verschillen1b.png']
follow_up_prompt = """Een proefpersoon is gevraagd om de verschillen te vinden tussen twee afbeeldingen.
De proefpersoon komt met het volgende antwoord:

<antwoord>
{antwoord}
</antwoord}

Het juiste antwoord is:
1. In de tweede afbeelding  mist een plank aan de linkerkant van het hek.
2. In de tweede afbeelding mist het zadel van het paard.
3. In tweede afbeelding heeft het paard een witte bles over de neus maar in de eerste afbeelding niet.
4. In de eerste afbeelding heeft de kat haar achterpoot naar beneden hangen maar in de tweede afbeelding is die omhoog getrokken.
5. In de eerste afbeelding is de trui van de man meer omhoog getrokken zodat je zijn heup ziet.
6. In de eerste afbeelding heeft de man een haarlok door zijn pet steken en in de tweede afbeelding mist die.
7. In de tweede afbeelding komt er een kuikentje uit een van de eieren.
8. In de eerste afbeelding heeft de koe een bruin haarstukje tussen haar hoorns, in de tweede afbelding mist dat.
9. In de tweede afbeelding mist de sluitmond van de gieter.
10. In de tweee afbeelding staat er een extra kuikenje naast de gieter.
11. In de eerste afbeelding staat het tweede kuikentje van links met zijn snavel naar link. In de tweede afbeelding is deze omgedraaid.
12. In de tweede afbeelding heeft de koe een witte vlek aan haar zijkant, in de eerste afbeelding niet.

Geef aan welke van deze twaalf antwoorden de proefpersoon goed had gevonden (true) of niet had gevonden (false) en geef me ook het aantal goede antwoorden.
Geef je antwoord in json in het volgende formaat:
{'antwoorden': [true, true, false, false, true, true, true true, false, false, false, true],
 'aantal_goed': 3}"""


[VERSCHILLEN2]
prompt = """Kijk goed naar deze twee afbeeldingen en geef me de verschillen.
Geef niet meteen antwoord maar bekijk elke regio van de afbeelding zorgvuldig. Bekijk per regio welke verschillen je ziet.
Als je de verschillen hebt gevonden, check ze dan. Zijn de afbeeldingen op dat punt echt verschillend?
Check tenslote of je nog verschillen hebt gemist. Ik wil ze zes hebben! Dat is heel belangrijk.
Stel geen vragen."""
image = ['input/verschillen2a.png', 'input/verschillen2b.png']
follow_up_prompt = """Een proefpersoon is gevraagd om de 6 verschillen te vinden tussen twee afbeeldingen.
De proefpersoon komt met het volgende antwoord:

<antwoord>
{antwoord}
</antwoord}

Het juiste antwoord is:
1. In de tweede afbeelding mist de ring om haar wijsvinger.
2. In de eerste afbeelding is haar riem bruin; in de tweede is deze blauw.
3. In de tweede afbeelding is de ketting om haar hals verdwenen.
4. Ook veranderde haar rechtse oog in een magisch paars oog.
5. Aan haar linkse wimper verdween er een klein stukje.
6. Het linkse oor is weg in afbeelding 2.

Geef aan welke van deze twaalf antwoorden de proefpersoon goed had gevonden (true) of niet had gevonden (false) en geef me ook het aantal goede antwoorden.
Geef je antwoord in json in het volgende formaat:
{'antwoorden': [true, true, false, false, true, true],
 'aantal_goed': 3}"""

[LOGIQUIZ]
prompt = """Amanda, Jack, Mike en Rachel reisden in vier verschillende jaren (2015, 2016, 2017 en 2018) naar vier verschillende locaties (Londen, Rio de Janeiro, Sydney, Tokio).
	1.	Noch Amanda noch Jack reisden in 2015.
	2.	Mike reisde niet naar Zuid-Amerika.
	3.	Mike reisde in 2017.
	4.	Amanda bezocht Londen.
	5.	Noch Mike noch Rachel reisden naar Japan.
	6.	Een man reisde in 2016.
Welke stad werd als eerste bezocht en door wie??
Geef je antwoord als json met als keys:
"bestemming": de stad die als eerste bezocht werd
"persoon": de naam van de persoon die die stad bezocht."""
json = true
answer = {bestemming = "Rio de Janeiro", persoon = "Rachel"}