[BEOORDELAAR]
json = false
answer_contains = 'boven de zuiger'
system = """Je bent een ervaren leraar autotechniek. Je doel is om mij zo goed en zo efficiënt mogelijk {subject} bij te brengen.
Ik volg een studie autotechniek op MBO of community college niveau.
Je bent vriendelijk, behulpzaam. Je schrijft in het Nederlands."""
prompt = """Ik wil dat je mijn antwoord in een examen beoordeelt.
Beschouw de volgende vraag en het antwoord van een expert, beiden tussen triple quotes:

Vraag: '''Wat laat het indicateurdiagram zien?'''
Expert antwoord: '''Het drukverloop boven de zuiger tijdens één arbeidscyclus.'''

Volg de volgende stappen:

1. Beschouw mijn antwoord: '''De druk in de zuiger.'''
en mijn correctie: '''tijdens een cyclus van de motor'''
Geef hier geen output over.

2. Voeg mijn antwoord en mijn correctie samen tot één antwoord.
Waar correctie en antwoord elkaar tegen spreken, kies je voor de correctie.
Geef hier geen output over.

3. Beoordeel dit samengevoegde antwoord door het te vergelijken met het antwoord van de expert.
Geef in je beoordeling aan waar ik kennis mis en leg uit hoe ik deze hiaten kan minimaliseren met behulp van voorbeelden uit de echte wereld.
Geef deze beoordeling als output.
Maak je tekst leerzaam, motiverend en inspirerend maar gebruik eenvoudige taal.
Gebruik maximaal 80 woorden.
Antwoord in het Nederlands."""


[VERTALER]
json = false
answer_contains = '%naam%'
system = """Je bent een vertaler. Je vertaalt software die bedoeld is voor de training van automonteurs.
De vertalingen bestaan soms uit hele zinnen maar soms ook uit losse woorden."""
prompt = """Vertaal de volgende 3 teksten naar Engels.

1 [[De eerste zin bestaat@@uit twee regels en nog een lege regel aan het eind@@]]
2 [[We luisterden naar de band maar hoorden geen gesis.]]
3 [[@@Hallo %naam%. Je hebt %aantal% nieuwe berichten.]]

**Belangrijke instructies voor de vertaling:**

- **Alleen tekst vertalen:** Vertaal enkel de tekst die zich bevindt tussen de dubbele vierkante haakjes `[[` en `]]`.
- **Behoud van speciale tekens:** Alle spaties, tabs, leestekens, `@@`, `###`, symbolen, en andere speciale tekens moeten exact behouden blijven zoals ze in de oorspronkelijke tekst staan.
- **Formatteerkenmerken behouden:** Als een tekst eindigt op `@@`, de vertaalde tekst moet ook eindigen op `@@`.

**Vertaalverzoek:**

Geef de vertalingen terug met behoud van de originele structuur, nummering, en formatteerkenmerken."""


[APPLES]
json = true
answer = {oplossing = 11}
prompt = """Ik had een aantal appels. Ik verloor er één. Daarna gaf ik de helft van wat ik over had weg.
Daarna at ik er drie op. Toen had ik er nog twee over. Hoeveel appels had ik aan het begin?

Werk stap voor stap aan dit probleem.
Geef me de output als json met als key: "oplossing" en als waarde het aantal appels.
Maar geef alleen json als output terug. Geen andere tekst ervoor of erna."""


[BALKON1]
prompt = """Geef me de oppervlakte van het balkon in vierkante meter. Geef je antwoord in json met als
key: 'oppervlakte' en als waarde de oppervlakte in vierkante meter afgerond op 2 cijfers achter de komma."""
image = 'input/balkon1.png'
json = true
answer = {oppervlakte = 6.84}

[TERRAS2]
prompt = """Geef me de oppervlakte van het dakterras in vierkante meter. Geef je antwoord in json met als
key: 'oppervlakte' en als waarde de oppervlakte in vierkante meter afgerond op 4 cijfers achter de komma."""
image = 'input/terras2.png'
json = true
answer = {oppervlakte = 3.7275}

[TERRAS3]
prompt = """Geef me de oppervlakte van het dakterras in vierkante meter. Geef je antwoord in json met als
key: 'oppervlakte' en als waarde de oppervlakte in vierkante meter afgerond op 4 cijfers achter de komma."""
image = 'input/terras3.png'
json = true
answer = {oppervlakte = 3.7275}

[HAZES]
prompt = """Geef me de naam van de Amsterdamse volkszanger uit de Pijp wiens kinderen ook zangers zijn."""
answer_contains = 'André Hazes'
json = false

[VERSCHILLEN1]
prompt = """Kijk goed naar deze twee afbeeldingen en geef me de 12 verschillen.
Geef niet meteen antwoord maar bekijk elke regio van de afbeelding zorgvuldig. Bekijk per regio welke verschillen je ziet.
Als je de verschillen hebt gevonden, check ze dan. Zijn de afbeeldingen op dat punt echt verschillend?
Check tenslote of je nog verschillen hebt gemist. Ik wil ze alle 12 hebben! Dat is heel belangrijk."""
image = ['input/verschillen1a.png', 'input/verschillen1b.png']
follow_up_prompt = """Een proefpersoon is gevraagd om de verschillen te vinden tussen twee afbeeldingen.
De proefpersoon komt met het volgende antwoord:

<antwoord>
{antwoord}
</antwoord}

Het juiste antwoord is:
1. In de tweede afbeelding  mist een plank aan de linkerkant van het hek.
2. In de tweede afbeelding mist het zadel van het paard.
3. In tweede afbeelding heeft het paard een witte bles over de neus maar in de eerste afbeelding niet.
4. In de eerste afbeelding heeft de kat haar achterpoot naar beneden hangen maar in de tweede afbeelding is die omhoog getrokken.
5. In de eerste afbeelding is de trui van de man meer omhoog getrokken zodat je zijn heup ziet.
6. In de eerste afbeelding heeft de man een haarlok door zijn pet steken en in de tweede afbeelding mist die.
7. In de tweede afbeelding komt er een kuikentje uit een van de eieren.
8. In de eerste afbeelding heeft de koe een bruin haarstukje tussen haar hoorns, in de tweede afbelding mist dat.
9. In de tweede afbeelding mist de sluitmond van de gieter.
10. In de tweee afbeelding staat er een extra kuikenje naast de gieter.
11. In de eerste afbeelding staat het tweede kuikentje van links met zijn snavel naar link. In de tweede afbeelding is deze omgedraaid.
12. In de tweede afbeelding heeft de koe een witte vlek aan haar zijkant, in de eerste afbeelding niet.

Geef aan welke van deze twaalf antwoorden de proefpersoon goed had gevonden (true) of niet had gevonden (false) en geef me ook het aantal goede antwoorden.
Geef je antwoord in json in het volgende formaat:
{'antwoorden': [true, true, false, false, true, true, true true, false, false, false, true],
 'aantal_goed': 3}"""


[VERSCHILLEN2]
prompt = """Kijk goed naar deze twee afbeeldingen en geef me de verschillen.
Geef niet meteen antwoord maar bekijk elke regio van de afbeelding zorgvuldig. Bekijk per regio welke verschillen je ziet.
Als je de verschillen hebt gevonden, check ze dan. Zijn de afbeeldingen op dat punt echt verschillend?
Check tenslote of je nog verschillen hebt gemist. Ik wil ze zes hebben! Dat is heel belangrijk."""
image = ['input/verschillen2a.png', 'input/verschillen2b.png']
follow_up_prompt = """Een proefpersoon is gevraagd om de 6 verschillen te vinden tussen twee afbeeldingen.
De proefpersoon komt met het volgende antwoord:

<antwoord>
{antwoord}
</antwoord}

Het juiste antwoord is:
1. In de tweede afbeelding mist de ring om haar wijsvinger.
2. In de eerste afbeelding is haar riem bruin; in de tweede is deze blauw.
3. In de tweede afbeelding is de ketting om haar hals verdwenen.
4. Ook veranderde haar rechtse oog in een magisch paars oog.
5. Aan haar linkse wimper verdween er een klein stukje.
6. Het linkse oor is weg in afbeelding 2.

Geef aan welke van deze twaalf antwoorden de proefpersoon goed had gevonden (true) of niet had gevonden (false) en geef me ook het aantal goede antwoorden.
Geef je antwoord in json in het volgende formaat:
{'antwoorden': [true, true, false, false, true, true],
 'aantal_goed': 3}"""

